import cuadernos from "@/assets/cat-cuadernos.jpg";

export const imagenGenerica = cuadernos;

export const imagenDe = (imageUrl: string | null) => imageUrl ?? imagenGenerica;

export const categorias: { id: string; label: string }[] = [
  { id: "todos", label: "Todos" },
  { id: "cuadernos", label: "Cuadernos" },
  { id: "colores", label: "Colores" },
  { id: "arte", label: "Arte" },
  { id: "pegantes", label: "Pegantes" },
  { id: "lapices", label: "Lápices" },
  { id: "plumones", label: "Plumones" },
  { id: "boligrafos", label: "Bolígrafos" },
  { id: "cintas", label: "Cintas" },
  { id: "reglas", label: "Reglas" },
  { id: "fomy", label: "Fomy" },
  { id: "tajalapices", label: "Tajalápices" },
  { id: "agendas", label: "Agendas" },
  { id: "blocks", label: "Blocks" },
  { id: "borradores", label: "Borradores" },
  { id: "plastilinas", label: "Plastilinas" },
  { id: "marcadores", label: "Marcadores" },
  { id: "temperas", label: "Témperas" },
  { id: "compases", label: "Compases" },
  { id: "correctores", label: "Correctores" },
  { id: "escuadras", label: "Escuadras" },
  { id: "sets", label: "Sets" },
  { id: "crayones", label: "Crayones" },
  { id: "esferos", label: "Esferos" },
  { id: "cartulinas", label: "Cartulinas" },
  { id: "papeles", label: "Papeles" },
  { id: "resaltadores", label: "Resaltadores" },
  { id: "carpetas", label: "Carpetas" },
  { id: "estuches", label: "Estuches" },
  { id: "tijeras", label: "Tijeras" },
  { id: "archivadores", label: "Archivadores" },
  { id: "portaminas", label: "Portaminas" },
  { id: "pinturas", label: "Pinturas" },
  { id: "curvigrafos", label: "Curvígrafos" },
  { id: "placas-de-dibujo", label: "Placas de dibujo" },
  { id: "transportadores", label: "Transportadores" },
  { id: "folders", label: "Folders" },
  { id: "kits-de-geometria", label: "Kits de geometría" },
  { id: "cartucheras", label: "Cartucheras" },
  { id: "forros", label: "Forros" },
  { id: "maletas-escolares", label: "Maletas escolares" },
  { id: "rotuladores", label: "Rotuladores" },
  { id: "contac", label: "Contac" },
  { id: "acuarelas", label: "Acuarelas" },
  { id: "micropuntas", label: "Micropuntas" },
  { id: "cajas-matematicas", label: "Cajas matemáticas" },
  { id: "loncheras", label: "Loncheras" },
  { id: "separadores", label: "Separadores" },
  { id: "pliegos", label: "Pliegos" },
  { id: "calculadoras", label: "Calculadoras" },
  { id: "tintas", label: "Tintas" },
  { id: "rollos", label: "Rollos" },
  { id: "oficina", label: "Oficina" },
  { id: "factureros", label: "Factureros" },
  { id: "talonarios", label: "Talonarios" },
  { id: "planilleros", label: "Planilleros" },
  { id: "didacticos", label: "Didácticos" },
  { id: "tableros", label: "Tableros" },
];

export const formatoCOP = (valor: number) =>
  new Intl.NumberFormat("es-CO", {
    style: "currency",
    currency: "COP",
    maximumFractionDigits: 0,
  }).format(valor);
